name: test
description: "This"
title: '[test]: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this incident report! Assign the team members involved and close the issue once the incident has ended.
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        | Link Contact person  | Description | URL |
        | ------------- | ------------- | ------------ |
        |  |  |  |
        |  |  |  |

